# todo datasource, redis, file 경로 수정해야함
spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url:
      username:
      password:
      minimumIdle: 5
      maximumPoolSize: 5
      poolName: HikariCP
      connection-test-query: SELECT 1
      idleTimeout: 10000
      connection-timeout: 10000
      validation-timeout: 10000
      max-lifetime: 177000  # 177초, hikari는 RDS wait_timeout(180초) 보다 2 ~ 3초 정도 짧게 줄 것을 권장
      leak-detection-threshold: 10000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: false
        useLocalSessionState: true
        useLocalTransactionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 5

logging:
  config: classpath:logback-dev.xml

file:
  upload:
    location: /app/file
    temp: temp/
    shell-ec2-to-s3-tmp-sync: /app/script/s3/01_ec2_to_s3_tmp_file_sync.sh
    shell-s3-tmp-to-s3-sync: /app/script/s3/02_s3_tmp_to_s3_bucket_sync.sh
    shell-s3-to-ec2-sync: /app/script/s3/03_s3_to_ec2_file_sync.sh
    # todo 버킷 이름, public/private url 수정해야함
    public-s3-bucket: dev-static-file-public
    private-s3-bucket: dev-static-file-private
    temp-s3-bucket: dev-static-file-temp
    public-url: http://localhost
    private-url: http://localhost